Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLCTD/MakeEMLCTD.R, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLCTD/edi.200.2.xml, MakeEMLCTD.R
Hi @cayelan. I've revised the EML record for data package edi.200 and have updated arguments to make_eml.R. The EML record edi.200.2.xml, and corresponding data, have passed evaluation but have not been uploaded. You will have to do this.
Best,
Colin
=> Revise EML for data package edi.200

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLCTD/edi.200.3.xml
Hi @cayelan. Here is the EML revision you originally requested.
Cheers,
Colin
=> Increment revision number

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/Variable_inspection_startYear_endYear.Rmd
I made a template for the EDI viz script
=> Add template for EDI viz script

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/Maintenance_Log_Template.txt
Made an template Maintenance Log for the EDI data packages to use
=> Updated template for the maintenance log

Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_working.R
Working through updates w/ ABP 👍 @abreefpilz
=> Updating scripts for EDI; got rid of archived code

Data/DataNotYetUploadedToEDI/Metals_Data/Metals_Maintenance_Log.txt, Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_working.R
added a section in to see if total and soluble samples had been switched and fix that
=> Check soluble and total sample in metals script

Data/DataNotYetUploadedToEDI/Raw_chla/Filt_Chla_Maintenance_Log.txt
Added observations to the maint log for this year's chla.
=> Added observations to the maint log for this year's chla.

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_GHG/GHG_inspection_2015_2023.Rmd
@abreefpilz @addelany my visualisation script
=> visual inspection script

Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_working.R, Scripts/L1_generation_scripts/filt_chla_qaqc.R, Scripts/L1_generation_scripts/ghg_qaqc.R
Fixed the header break in the maintenance for loop so the function will load and not stop halfway through
=> Fix header break in maint for loop

Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_working.R
@abreefpilz @addelany @carlybauer  I have updated my code with info about the threshold for switched samples. We would like to test to see if Fe, Al, and Si are switched. They are "switched" if the solubles are greater than totals plus 3 MRL. If all three have been switched, then all columns should be switched.  I will also Slack you info. Thanks! :thinking: :zany_face:
=> Adding comments about MRL threshold for switched samples

Data/DataNotYetUploadedToEDI/Metals_Data/Metals_Maintenance_Log.csv
@addelany @abreefpilz :call_me_hand:
=> Editing maintenance log to include some errant data from 2020

Data/DataNotYetUploadedToEDI/Metals_Data/MRL_metals.txt
Edited this .txt file to prepare for metal staging
=> Updated to match what metals we are publishing

Scripts/L1_functions/ysi_create.R
=> ugh edited the wrong qaqc script - this should work now

Data/DataNotYetUploadedToEDI/Metals_Data/Metals_Maintenance_Log.csv
@addelany @abreefpilz This pull request has two commits because I forgot to fill in some of the columns for the new entries... whoops! The metals maintenance log should be complete now.
=> Adding missing digestion data to metals maintenance log

Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_working.R
=> Add in flag when samples were switched

Data/DataNotYetUploadedToEDI/Metals_Data/Metals_Maintenance_Log.csv, Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_working.R
=> adding maintenance log and other EDI things

Data/DataNotYetUploadedToEDI/EddyFlux_Processing/FCR_Process_BD_Markdown.Rmd
Just learning pull request. You can ignore it! @abreefpilz
=> practice pull request

Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/ABP_heatmap_for_Cece_20241018.Rmd
@ceceliawood code to make sed trap figures
=> Plots for Cece sed. manuscript

Scripts/L1_functions/ghg_create.R, Scripts/L1_generation_scripts/ghg_qaqc.R
Fixing up the GHG QAQC function
- changed the MDL so it is rolling and looks back at the previous 2 years for the current year
- kept the flags in the historical file
- added a saved file with all of the notes from observations and so it is easier to add to the maintenance log
=> Fixing a few things for the GHG function

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLmetals/2025/personnel.txt
=> updated grants

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLmetals/2025/Metals_maintenancelog_2014_2024.csv
=> Updated maintenance log

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_ManualDischarge/2024/MakeEML_manual-discharge_2024.R, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_ManualDischarge/2024/edi.1017.18.xml, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_ManualDischarge/2024/edi.454.8.xml
=> publish manual Q :fireworks:

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_Sed_trap/2025/keywords.txt, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLmetals/2025/keywords.txt
=> Adding new keyword for both sed traps and metals

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_GHG/2024/MakeEMLGHG.R, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_GHG/2024/attributes_ghg_maintenancelog_2015_2024.txt, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_GHG/2024/edi.551.9.xml, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_GHG/2024/ghg_maintenancelog_2015_2024.csv
=> ghgs published!

.gitignore, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLFluoroProbe/2024/FluoroProbe_qaqc_2014_2024.R, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLFluoroProbe/2024/MakeEMLFluoroProbe.R, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLFluoroProbe/2024/edi.1139.7.xml, Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEMLFluoroProbe/2024/fluoroprobe_maintenance_2014_2024.csv, Data/DataNotYetUploadedToEDI/FluoroProbe/fluoroprobe_maintenance.csv, Scripts/L1_functions/fluoroprobe_create.R
@cayelan @addelany @abreefpilz thank you!
=> getting FP back to staging

Data/DataNotYetUploadedToEDI/EddyFlux_Processing/FCR_Process_BD_Markdown.Rmd
@abreefpilz changes and updates to EddyFlux post processing script (FCR _Process_BD_Markdown.Rmd)
=> EddyFlux post processing script updated 2025!

Data/DataNotYetUploadedToEDI/EddyFlux_Processing/FCR_Process_BD_Markdown.Rmd
=> met link updated from staging to production!

Data/DataAlreadyUploadedToEDI/EDIProductionFiles/MakeEML_EddyFlux/2024/MakeEML_eddy-flux.R
Don't know what happened to this file.
=> Adding the make EML function in

Scripts/L1_functions/metals_create.R
Removed ISCO samples that were not digested and rerun after being digested
=> removed dup ISCO samples

Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_Sample_Depth.csv
=> Adding new metals depth codes to reflect water level decrease in BVR

Data/DataNotYetUploadedToEDI/Metals_Data/Scripts/Metals_Sample_Depth.csv
=> Adding codes for new Carvins sites

Scripts/WVWA_cells_to_conc.Rmd
Did this for Ryan C's workshop with the Water Authority
=> Converting EXO data to cells per mL
